/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { MockParaSwapAugustus } from "./MockParaSwapAugustus";
export type { MockParaSwapAugustusRegistry } from "./MockParaSwapAugustusRegistry";
export type { MockParaSwapTokenTransferProxy } from "./MockParaSwapTokenTransferProxy";
export type { MockUniswapV2Router02 } from "./MockUniswapV2Router02";
