/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../../common";

export interface MockParaSwapAugustusInterface extends utils.Interface {
  functions: {
    "expectSwap(address,address,uint256,uint256,uint256)": FunctionFragment;
    "getTokenTransferProxy()": FunctionFragment;
    "swap(address,address,uint256,uint256)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic: "expectSwap" | "getTokenTransferProxy" | "swap"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "expectSwap",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "getTokenTransferProxy",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "swap",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;

  decodeFunctionResult(functionFragment: "expectSwap", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getTokenTransferProxy",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "swap", data: BytesLike): Result;

  events: {};
}

export interface MockParaSwapAugustus extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: MockParaSwapAugustusInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    expectSwap(
      fromToken: PromiseOrValue<string>,
      toToken: PromiseOrValue<string>,
      fromAmountMin: PromiseOrValue<BigNumberish>,
      fromAmountMax: PromiseOrValue<BigNumberish>,
      receivedAmount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    getTokenTransferProxy(overrides?: CallOverrides): Promise<[string]>;

    swap(
      fromToken: PromiseOrValue<string>,
      toToken: PromiseOrValue<string>,
      fromAmount: PromiseOrValue<BigNumberish>,
      toAmount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  expectSwap(
    fromToken: PromiseOrValue<string>,
    toToken: PromiseOrValue<string>,
    fromAmountMin: PromiseOrValue<BigNumberish>,
    fromAmountMax: PromiseOrValue<BigNumberish>,
    receivedAmount: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  getTokenTransferProxy(overrides?: CallOverrides): Promise<string>;

  swap(
    fromToken: PromiseOrValue<string>,
    toToken: PromiseOrValue<string>,
    fromAmount: PromiseOrValue<BigNumberish>,
    toAmount: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    expectSwap(
      fromToken: PromiseOrValue<string>,
      toToken: PromiseOrValue<string>,
      fromAmountMin: PromiseOrValue<BigNumberish>,
      fromAmountMax: PromiseOrValue<BigNumberish>,
      receivedAmount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    getTokenTransferProxy(overrides?: CallOverrides): Promise<string>;

    swap(
      fromToken: PromiseOrValue<string>,
      toToken: PromiseOrValue<string>,
      fromAmount: PromiseOrValue<BigNumberish>,
      toAmount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  filters: {};

  estimateGas: {
    expectSwap(
      fromToken: PromiseOrValue<string>,
      toToken: PromiseOrValue<string>,
      fromAmountMin: PromiseOrValue<BigNumberish>,
      fromAmountMax: PromiseOrValue<BigNumberish>,
      receivedAmount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    getTokenTransferProxy(overrides?: CallOverrides): Promise<BigNumber>;

    swap(
      fromToken: PromiseOrValue<string>,
      toToken: PromiseOrValue<string>,
      fromAmount: PromiseOrValue<BigNumberish>,
      toAmount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    expectSwap(
      fromToken: PromiseOrValue<string>,
      toToken: PromiseOrValue<string>,
      fromAmountMin: PromiseOrValue<BigNumberish>,
      fromAmountMax: PromiseOrValue<BigNumberish>,
      receivedAmount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    getTokenTransferProxy(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    swap(
      fromToken: PromiseOrValue<string>,
      toToken: PromiseOrValue<string>,
      fromAmount: PromiseOrValue<BigNumberish>,
      toAmount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
