/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumber, Signer, utils } from "ethers";
import type { EventFragment } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../common";

export interface ILendingPoolConfiguratorInterface extends utils.Interface {
  functions: {};

  events: {
    "ATokenUpgraded(address,address,address)": EventFragment;
    "BorrowingDisabledOnReserve(address)": EventFragment;
    "BorrowingEnabledOnReserve(address,bool)": EventFragment;
    "CollateralConfigurationChanged(address,uint256,uint256,uint256)": EventFragment;
    "ReserveActivated(address)": EventFragment;
    "ReserveDeactivated(address)": EventFragment;
    "ReserveDecimalsChanged(address,uint256)": EventFragment;
    "ReserveFactorChanged(address,uint256)": EventFragment;
    "ReserveFrozen(address)": EventFragment;
    "ReserveInitialized(address,address,address,address,address)": EventFragment;
    "ReserveInterestRateStrategyChanged(address,address)": EventFragment;
    "ReserveUnfrozen(address)": EventFragment;
    "StableDebtTokenUpgraded(address,address,address)": EventFragment;
    "StableRateDisabledOnReserve(address)": EventFragment;
    "StableRateEnabledOnReserve(address)": EventFragment;
    "VariableDebtTokenUpgraded(address,address,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "ATokenUpgraded"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "BorrowingDisabledOnReserve"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "BorrowingEnabledOnReserve"): EventFragment;
  getEvent(
    nameOrSignatureOrTopic: "CollateralConfigurationChanged"
  ): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ReserveActivated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ReserveDeactivated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ReserveDecimalsChanged"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ReserveFactorChanged"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ReserveFrozen"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ReserveInitialized"): EventFragment;
  getEvent(
    nameOrSignatureOrTopic: "ReserveInterestRateStrategyChanged"
  ): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ReserveUnfrozen"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "StableDebtTokenUpgraded"): EventFragment;
  getEvent(
    nameOrSignatureOrTopic: "StableRateDisabledOnReserve"
  ): EventFragment;
  getEvent(nameOrSignatureOrTopic: "StableRateEnabledOnReserve"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "VariableDebtTokenUpgraded"): EventFragment;
}

export interface ATokenUpgradedEventObject {
  asset: string;
  proxy: string;
  implementation: string;
}
export type ATokenUpgradedEvent = TypedEvent<
  [string, string, string],
  ATokenUpgradedEventObject
>;

export type ATokenUpgradedEventFilter = TypedEventFilter<ATokenUpgradedEvent>;

export interface BorrowingDisabledOnReserveEventObject {
  asset: string;
}
export type BorrowingDisabledOnReserveEvent = TypedEvent<
  [string],
  BorrowingDisabledOnReserveEventObject
>;

export type BorrowingDisabledOnReserveEventFilter =
  TypedEventFilter<BorrowingDisabledOnReserveEvent>;

export interface BorrowingEnabledOnReserveEventObject {
  asset: string;
  stableRateEnabled: boolean;
}
export type BorrowingEnabledOnReserveEvent = TypedEvent<
  [string, boolean],
  BorrowingEnabledOnReserveEventObject
>;

export type BorrowingEnabledOnReserveEventFilter =
  TypedEventFilter<BorrowingEnabledOnReserveEvent>;

export interface CollateralConfigurationChangedEventObject {
  asset: string;
  ltv: BigNumber;
  liquidationThreshold: BigNumber;
  liquidationBonus: BigNumber;
}
export type CollateralConfigurationChangedEvent = TypedEvent<
  [string, BigNumber, BigNumber, BigNumber],
  CollateralConfigurationChangedEventObject
>;

export type CollateralConfigurationChangedEventFilter =
  TypedEventFilter<CollateralConfigurationChangedEvent>;

export interface ReserveActivatedEventObject {
  asset: string;
}
export type ReserveActivatedEvent = TypedEvent<
  [string],
  ReserveActivatedEventObject
>;

export type ReserveActivatedEventFilter =
  TypedEventFilter<ReserveActivatedEvent>;

export interface ReserveDeactivatedEventObject {
  asset: string;
}
export type ReserveDeactivatedEvent = TypedEvent<
  [string],
  ReserveDeactivatedEventObject
>;

export type ReserveDeactivatedEventFilter =
  TypedEventFilter<ReserveDeactivatedEvent>;

export interface ReserveDecimalsChangedEventObject {
  asset: string;
  decimals: BigNumber;
}
export type ReserveDecimalsChangedEvent = TypedEvent<
  [string, BigNumber],
  ReserveDecimalsChangedEventObject
>;

export type ReserveDecimalsChangedEventFilter =
  TypedEventFilter<ReserveDecimalsChangedEvent>;

export interface ReserveFactorChangedEventObject {
  asset: string;
  factor: BigNumber;
}
export type ReserveFactorChangedEvent = TypedEvent<
  [string, BigNumber],
  ReserveFactorChangedEventObject
>;

export type ReserveFactorChangedEventFilter =
  TypedEventFilter<ReserveFactorChangedEvent>;

export interface ReserveFrozenEventObject {
  asset: string;
}
export type ReserveFrozenEvent = TypedEvent<[string], ReserveFrozenEventObject>;

export type ReserveFrozenEventFilter = TypedEventFilter<ReserveFrozenEvent>;

export interface ReserveInitializedEventObject {
  asset: string;
  aToken: string;
  stableDebtToken: string;
  variableDebtToken: string;
  interestRateStrategyAddress: string;
}
export type ReserveInitializedEvent = TypedEvent<
  [string, string, string, string, string],
  ReserveInitializedEventObject
>;

export type ReserveInitializedEventFilter =
  TypedEventFilter<ReserveInitializedEvent>;

export interface ReserveInterestRateStrategyChangedEventObject {
  asset: string;
  strategy: string;
}
export type ReserveInterestRateStrategyChangedEvent = TypedEvent<
  [string, string],
  ReserveInterestRateStrategyChangedEventObject
>;

export type ReserveInterestRateStrategyChangedEventFilter =
  TypedEventFilter<ReserveInterestRateStrategyChangedEvent>;

export interface ReserveUnfrozenEventObject {
  asset: string;
}
export type ReserveUnfrozenEvent = TypedEvent<
  [string],
  ReserveUnfrozenEventObject
>;

export type ReserveUnfrozenEventFilter = TypedEventFilter<ReserveUnfrozenEvent>;

export interface StableDebtTokenUpgradedEventObject {
  asset: string;
  proxy: string;
  implementation: string;
}
export type StableDebtTokenUpgradedEvent = TypedEvent<
  [string, string, string],
  StableDebtTokenUpgradedEventObject
>;

export type StableDebtTokenUpgradedEventFilter =
  TypedEventFilter<StableDebtTokenUpgradedEvent>;

export interface StableRateDisabledOnReserveEventObject {
  asset: string;
}
export type StableRateDisabledOnReserveEvent = TypedEvent<
  [string],
  StableRateDisabledOnReserveEventObject
>;

export type StableRateDisabledOnReserveEventFilter =
  TypedEventFilter<StableRateDisabledOnReserveEvent>;

export interface StableRateEnabledOnReserveEventObject {
  asset: string;
}
export type StableRateEnabledOnReserveEvent = TypedEvent<
  [string],
  StableRateEnabledOnReserveEventObject
>;

export type StableRateEnabledOnReserveEventFilter =
  TypedEventFilter<StableRateEnabledOnReserveEvent>;

export interface VariableDebtTokenUpgradedEventObject {
  asset: string;
  proxy: string;
  implementation: string;
}
export type VariableDebtTokenUpgradedEvent = TypedEvent<
  [string, string, string],
  VariableDebtTokenUpgradedEventObject
>;

export type VariableDebtTokenUpgradedEventFilter =
  TypedEventFilter<VariableDebtTokenUpgradedEvent>;

export interface ILendingPoolConfigurator extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: ILendingPoolConfiguratorInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {};

  callStatic: {};

  filters: {
    "ATokenUpgraded(address,address,address)"(
      asset?: PromiseOrValue<string> | null,
      proxy?: PromiseOrValue<string> | null,
      implementation?: PromiseOrValue<string> | null
    ): ATokenUpgradedEventFilter;
    ATokenUpgraded(
      asset?: PromiseOrValue<string> | null,
      proxy?: PromiseOrValue<string> | null,
      implementation?: PromiseOrValue<string> | null
    ): ATokenUpgradedEventFilter;

    "BorrowingDisabledOnReserve(address)"(
      asset?: PromiseOrValue<string> | null
    ): BorrowingDisabledOnReserveEventFilter;
    BorrowingDisabledOnReserve(
      asset?: PromiseOrValue<string> | null
    ): BorrowingDisabledOnReserveEventFilter;

    "BorrowingEnabledOnReserve(address,bool)"(
      asset?: PromiseOrValue<string> | null,
      stableRateEnabled?: null
    ): BorrowingEnabledOnReserveEventFilter;
    BorrowingEnabledOnReserve(
      asset?: PromiseOrValue<string> | null,
      stableRateEnabled?: null
    ): BorrowingEnabledOnReserveEventFilter;

    "CollateralConfigurationChanged(address,uint256,uint256,uint256)"(
      asset?: PromiseOrValue<string> | null,
      ltv?: null,
      liquidationThreshold?: null,
      liquidationBonus?: null
    ): CollateralConfigurationChangedEventFilter;
    CollateralConfigurationChanged(
      asset?: PromiseOrValue<string> | null,
      ltv?: null,
      liquidationThreshold?: null,
      liquidationBonus?: null
    ): CollateralConfigurationChangedEventFilter;

    "ReserveActivated(address)"(
      asset?: PromiseOrValue<string> | null
    ): ReserveActivatedEventFilter;
    ReserveActivated(
      asset?: PromiseOrValue<string> | null
    ): ReserveActivatedEventFilter;

    "ReserveDeactivated(address)"(
      asset?: PromiseOrValue<string> | null
    ): ReserveDeactivatedEventFilter;
    ReserveDeactivated(
      asset?: PromiseOrValue<string> | null
    ): ReserveDeactivatedEventFilter;

    "ReserveDecimalsChanged(address,uint256)"(
      asset?: PromiseOrValue<string> | null,
      decimals?: null
    ): ReserveDecimalsChangedEventFilter;
    ReserveDecimalsChanged(
      asset?: PromiseOrValue<string> | null,
      decimals?: null
    ): ReserveDecimalsChangedEventFilter;

    "ReserveFactorChanged(address,uint256)"(
      asset?: PromiseOrValue<string> | null,
      factor?: null
    ): ReserveFactorChangedEventFilter;
    ReserveFactorChanged(
      asset?: PromiseOrValue<string> | null,
      factor?: null
    ): ReserveFactorChangedEventFilter;

    "ReserveFrozen(address)"(
      asset?: PromiseOrValue<string> | null
    ): ReserveFrozenEventFilter;
    ReserveFrozen(
      asset?: PromiseOrValue<string> | null
    ): ReserveFrozenEventFilter;

    "ReserveInitialized(address,address,address,address,address)"(
      asset?: PromiseOrValue<string> | null,
      aToken?: PromiseOrValue<string> | null,
      stableDebtToken?: null,
      variableDebtToken?: null,
      interestRateStrategyAddress?: null
    ): ReserveInitializedEventFilter;
    ReserveInitialized(
      asset?: PromiseOrValue<string> | null,
      aToken?: PromiseOrValue<string> | null,
      stableDebtToken?: null,
      variableDebtToken?: null,
      interestRateStrategyAddress?: null
    ): ReserveInitializedEventFilter;

    "ReserveInterestRateStrategyChanged(address,address)"(
      asset?: PromiseOrValue<string> | null,
      strategy?: null
    ): ReserveInterestRateStrategyChangedEventFilter;
    ReserveInterestRateStrategyChanged(
      asset?: PromiseOrValue<string> | null,
      strategy?: null
    ): ReserveInterestRateStrategyChangedEventFilter;

    "ReserveUnfrozen(address)"(
      asset?: PromiseOrValue<string> | null
    ): ReserveUnfrozenEventFilter;
    ReserveUnfrozen(
      asset?: PromiseOrValue<string> | null
    ): ReserveUnfrozenEventFilter;

    "StableDebtTokenUpgraded(address,address,address)"(
      asset?: PromiseOrValue<string> | null,
      proxy?: PromiseOrValue<string> | null,
      implementation?: PromiseOrValue<string> | null
    ): StableDebtTokenUpgradedEventFilter;
    StableDebtTokenUpgraded(
      asset?: PromiseOrValue<string> | null,
      proxy?: PromiseOrValue<string> | null,
      implementation?: PromiseOrValue<string> | null
    ): StableDebtTokenUpgradedEventFilter;

    "StableRateDisabledOnReserve(address)"(
      asset?: PromiseOrValue<string> | null
    ): StableRateDisabledOnReserveEventFilter;
    StableRateDisabledOnReserve(
      asset?: PromiseOrValue<string> | null
    ): StableRateDisabledOnReserveEventFilter;

    "StableRateEnabledOnReserve(address)"(
      asset?: PromiseOrValue<string> | null
    ): StableRateEnabledOnReserveEventFilter;
    StableRateEnabledOnReserve(
      asset?: PromiseOrValue<string> | null
    ): StableRateEnabledOnReserveEventFilter;

    "VariableDebtTokenUpgraded(address,address,address)"(
      asset?: PromiseOrValue<string> | null,
      proxy?: PromiseOrValue<string> | null,
      implementation?: PromiseOrValue<string> | null
    ): VariableDebtTokenUpgradedEventFilter;
    VariableDebtTokenUpgraded(
      asset?: PromiseOrValue<string> | null,
      proxy?: PromiseOrValue<string> | null,
      implementation?: PromiseOrValue<string> | null
    ): VariableDebtTokenUpgradedEventFilter;
  };

  estimateGas: {};

  populateTransaction: {};
}
