/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../../common";

export interface GenericOracleIInterface extends utils.Interface {
  functions: {
    "getAssetPrice(address)": FunctionFragment;
    "getEthUsdPrice()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic: "getAssetPrice" | "getEthUsdPrice"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "getAssetPrice",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "getEthUsdPrice",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "getAssetPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEthUsdPrice",
    data: BytesLike
  ): Result;

  events: {
    "AssetPriceUpdated(address,uint256,uint256)": EventFragment;
    "EthPriceUpdated(uint256,uint256)": EventFragment;
    "ProphecySubmitted(address,address,uint96,uint96)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "AssetPriceUpdated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "EthPriceUpdated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ProphecySubmitted"): EventFragment;
}

export interface AssetPriceUpdatedEventObject {
  _asset: string;
  _price: BigNumber;
  timestamp: BigNumber;
}
export type AssetPriceUpdatedEvent = TypedEvent<
  [string, BigNumber, BigNumber],
  AssetPriceUpdatedEventObject
>;

export type AssetPriceUpdatedEventFilter =
  TypedEventFilter<AssetPriceUpdatedEvent>;

export interface EthPriceUpdatedEventObject {
  _price: BigNumber;
  timestamp: BigNumber;
}
export type EthPriceUpdatedEvent = TypedEvent<
  [BigNumber, BigNumber],
  EthPriceUpdatedEventObject
>;

export type EthPriceUpdatedEventFilter = TypedEventFilter<EthPriceUpdatedEvent>;

export interface ProphecySubmittedEventObject {
  _sybil: string;
  _asset: string;
  _sybilProphecy: BigNumber;
  _oracleProphecy: BigNumber;
}
export type ProphecySubmittedEvent = TypedEvent<
  [string, string, BigNumber, BigNumber],
  ProphecySubmittedEventObject
>;

export type ProphecySubmittedEventFilter =
  TypedEventFilter<ProphecySubmittedEvent>;

export interface GenericOracleI extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: GenericOracleIInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    getAssetPrice(
      _asset: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getEthUsdPrice(overrides?: CallOverrides): Promise<[BigNumber]>;
  };

  getAssetPrice(
    _asset: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getEthUsdPrice(overrides?: CallOverrides): Promise<BigNumber>;

  callStatic: {
    getAssetPrice(
      _asset: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getEthUsdPrice(overrides?: CallOverrides): Promise<BigNumber>;
  };

  filters: {
    "AssetPriceUpdated(address,uint256,uint256)"(
      _asset?: null,
      _price?: null,
      timestamp?: null
    ): AssetPriceUpdatedEventFilter;
    AssetPriceUpdated(
      _asset?: null,
      _price?: null,
      timestamp?: null
    ): AssetPriceUpdatedEventFilter;

    "EthPriceUpdated(uint256,uint256)"(
      _price?: null,
      timestamp?: null
    ): EthPriceUpdatedEventFilter;
    EthPriceUpdated(
      _price?: null,
      timestamp?: null
    ): EthPriceUpdatedEventFilter;

    "ProphecySubmitted(address,address,uint96,uint96)"(
      _sybil?: PromiseOrValue<string> | null,
      _asset?: PromiseOrValue<string> | null,
      _sybilProphecy?: null,
      _oracleProphecy?: null
    ): ProphecySubmittedEventFilter;
    ProphecySubmitted(
      _sybil?: PromiseOrValue<string> | null,
      _asset?: PromiseOrValue<string> | null,
      _sybilProphecy?: null,
      _oracleProphecy?: null
    ): ProphecySubmittedEventFilter;
  };

  estimateGas: {
    getAssetPrice(
      _asset: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getEthUsdPrice(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    getAssetPrice(
      _asset: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getEthUsdPrice(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
