/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../../common";

export interface IExtendedPriceAggregatorInterface extends utils.Interface {
  functions: {
    "getPlatformId()": FunctionFragment;
    "getSubTokens()": FunctionFragment;
    "getToken()": FunctionFragment;
    "getTokenType()": FunctionFragment;
    "latestAnswer()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "getPlatformId"
      | "getSubTokens"
      | "getToken"
      | "getTokenType"
      | "latestAnswer"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "getPlatformId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getSubTokens",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "getToken", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getTokenType",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "latestAnswer",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "getPlatformId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSubTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getToken", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getTokenType",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "latestAnswer",
    data: BytesLike
  ): Result;

  events: {
    "AnswerUpdated(int256,uint256,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "AnswerUpdated"): EventFragment;
}

export interface AnswerUpdatedEventObject {
  current: BigNumber;
  roundId: BigNumber;
  timestamp: BigNumber;
}
export type AnswerUpdatedEvent = TypedEvent<
  [BigNumber, BigNumber, BigNumber],
  AnswerUpdatedEventObject
>;

export type AnswerUpdatedEventFilter = TypedEventFilter<AnswerUpdatedEvent>;

export interface IExtendedPriceAggregator extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IExtendedPriceAggregatorInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    getPlatformId(overrides?: CallOverrides): Promise<[BigNumber]>;

    getSubTokens(overrides?: CallOverrides): Promise<[string[]]>;

    getToken(overrides?: CallOverrides): Promise<[string]>;

    getTokenType(overrides?: CallOverrides): Promise<[BigNumber]>;

    latestAnswer(overrides?: CallOverrides): Promise<[BigNumber]>;
  };

  getPlatformId(overrides?: CallOverrides): Promise<BigNumber>;

  getSubTokens(overrides?: CallOverrides): Promise<string[]>;

  getToken(overrides?: CallOverrides): Promise<string>;

  getTokenType(overrides?: CallOverrides): Promise<BigNumber>;

  latestAnswer(overrides?: CallOverrides): Promise<BigNumber>;

  callStatic: {
    getPlatformId(overrides?: CallOverrides): Promise<BigNumber>;

    getSubTokens(overrides?: CallOverrides): Promise<string[]>;

    getToken(overrides?: CallOverrides): Promise<string>;

    getTokenType(overrides?: CallOverrides): Promise<BigNumber>;

    latestAnswer(overrides?: CallOverrides): Promise<BigNumber>;
  };

  filters: {
    "AnswerUpdated(int256,uint256,uint256)"(
      current?: PromiseOrValue<BigNumberish> | null,
      roundId?: PromiseOrValue<BigNumberish> | null,
      timestamp?: null
    ): AnswerUpdatedEventFilter;
    AnswerUpdated(
      current?: PromiseOrValue<BigNumberish> | null,
      roundId?: PromiseOrValue<BigNumberish> | null,
      timestamp?: null
    ): AnswerUpdatedEventFilter;
  };

  estimateGas: {
    getPlatformId(overrides?: CallOverrides): Promise<BigNumber>;

    getSubTokens(overrides?: CallOverrides): Promise<BigNumber>;

    getToken(overrides?: CallOverrides): Promise<BigNumber>;

    getTokenType(overrides?: CallOverrides): Promise<BigNumber>;

    latestAnswer(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    getPlatformId(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getSubTokens(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getToken(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getTokenType(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    latestAnswer(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
