/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as clAggregators from "./CLAggregators";
export type { clAggregators };
export type { ChainlinkUSDETHOracleI } from "./ChainlinkUSDETHOracleI";
export type { GenericOracleI } from "./GenericOracleI";
export type { IExtendedPriceAggregator } from "./IExtendedPriceAggregator";
export type { LendingRateOracle } from "./LendingRateOracle";
export type { PriceOracle } from "./PriceOracle";
