/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../../common";

export declare namespace IUiPoolDataProvider {
  export type AggregatedReserveDataStruct = {
    underlyingAsset: PromiseOrValue<string>;
    name: PromiseOrValue<string>;
    symbol: PromiseOrValue<string>;
    decimals: PromiseOrValue<BigNumberish>;
    baseLTVasCollateral: PromiseOrValue<BigNumberish>;
    reserveLiquidationThreshold: PromiseOrValue<BigNumberish>;
    reserveLiquidationBonus: PromiseOrValue<BigNumberish>;
    reserveFactor: PromiseOrValue<BigNumberish>;
    usageAsCollateralEnabled: PromiseOrValue<boolean>;
    borrowingEnabled: PromiseOrValue<boolean>;
    stableBorrowRateEnabled: PromiseOrValue<boolean>;
    isActive: PromiseOrValue<boolean>;
    isFrozen: PromiseOrValue<boolean>;
    liquidityIndex: PromiseOrValue<BigNumberish>;
    variableBorrowIndex: PromiseOrValue<BigNumberish>;
    liquidityRate: PromiseOrValue<BigNumberish>;
    variableBorrowRate: PromiseOrValue<BigNumberish>;
    stableBorrowRate: PromiseOrValue<BigNumberish>;
    lastUpdateTimestamp: PromiseOrValue<BigNumberish>;
    aTokenAddress: PromiseOrValue<string>;
    stableDebtTokenAddress: PromiseOrValue<string>;
    variableDebtTokenAddress: PromiseOrValue<string>;
    interestRateStrategyAddress: PromiseOrValue<string>;
    availableLiquidity: PromiseOrValue<BigNumberish>;
    totalPrincipalStableDebt: PromiseOrValue<BigNumberish>;
    averageStableRate: PromiseOrValue<BigNumberish>;
    stableDebtLastUpdateTimestamp: PromiseOrValue<BigNumberish>;
    totalScaledVariableDebt: PromiseOrValue<BigNumberish>;
    priceInEth: PromiseOrValue<BigNumberish>;
    variableRateSlope1: PromiseOrValue<BigNumberish>;
    variableRateSlope2: PromiseOrValue<BigNumberish>;
    stableRateSlope1: PromiseOrValue<BigNumberish>;
    stableRateSlope2: PromiseOrValue<BigNumberish>;
    aEmissionPerSecond: PromiseOrValue<BigNumberish>;
    vEmissionPerSecond: PromiseOrValue<BigNumberish>;
    sEmissionPerSecond: PromiseOrValue<BigNumberish>;
    aIncentivesLastUpdateTimestamp: PromiseOrValue<BigNumberish>;
    vIncentivesLastUpdateTimestamp: PromiseOrValue<BigNumberish>;
    sIncentivesLastUpdateTimestamp: PromiseOrValue<BigNumberish>;
    aTokenIncentivesIndex: PromiseOrValue<BigNumberish>;
    vTokenIncentivesIndex: PromiseOrValue<BigNumberish>;
    sTokenIncentivesIndex: PromiseOrValue<BigNumberish>;
  };

  export type AggregatedReserveDataStructOutput = [
    string,
    string,
    string,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    boolean,
    boolean,
    boolean,
    boolean,
    boolean,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    number,
    string,
    string,
    string,
    string,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber
  ] & {
    underlyingAsset: string;
    name: string;
    symbol: string;
    decimals: BigNumber;
    baseLTVasCollateral: BigNumber;
    reserveLiquidationThreshold: BigNumber;
    reserveLiquidationBonus: BigNumber;
    reserveFactor: BigNumber;
    usageAsCollateralEnabled: boolean;
    borrowingEnabled: boolean;
    stableBorrowRateEnabled: boolean;
    isActive: boolean;
    isFrozen: boolean;
    liquidityIndex: BigNumber;
    variableBorrowIndex: BigNumber;
    liquidityRate: BigNumber;
    variableBorrowRate: BigNumber;
    stableBorrowRate: BigNumber;
    lastUpdateTimestamp: number;
    aTokenAddress: string;
    stableDebtTokenAddress: string;
    variableDebtTokenAddress: string;
    interestRateStrategyAddress: string;
    availableLiquidity: BigNumber;
    totalPrincipalStableDebt: BigNumber;
    averageStableRate: BigNumber;
    stableDebtLastUpdateTimestamp: BigNumber;
    totalScaledVariableDebt: BigNumber;
    priceInEth: BigNumber;
    variableRateSlope1: BigNumber;
    variableRateSlope2: BigNumber;
    stableRateSlope1: BigNumber;
    stableRateSlope2: BigNumber;
    aEmissionPerSecond: BigNumber;
    vEmissionPerSecond: BigNumber;
    sEmissionPerSecond: BigNumber;
    aIncentivesLastUpdateTimestamp: BigNumber;
    vIncentivesLastUpdateTimestamp: BigNumber;
    sIncentivesLastUpdateTimestamp: BigNumber;
    aTokenIncentivesIndex: BigNumber;
    vTokenIncentivesIndex: BigNumber;
    sTokenIncentivesIndex: BigNumber;
  };

  export type UserReserveDataStruct = {
    underlyingAsset: PromiseOrValue<string>;
    scaledATokenBalance: PromiseOrValue<BigNumberish>;
    usageAsCollateralEnabledOnUser: PromiseOrValue<boolean>;
    stableBorrowRate: PromiseOrValue<BigNumberish>;
    scaledVariableDebt: PromiseOrValue<BigNumberish>;
    principalStableDebt: PromiseOrValue<BigNumberish>;
    stableBorrowLastUpdateTimestamp: PromiseOrValue<BigNumberish>;
    aTokenincentivesUserIndex: PromiseOrValue<BigNumberish>;
    vTokenincentivesUserIndex: PromiseOrValue<BigNumberish>;
    sTokenincentivesUserIndex: PromiseOrValue<BigNumberish>;
  };

  export type UserReserveDataStructOutput = [
    string,
    BigNumber,
    boolean,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber
  ] & {
    underlyingAsset: string;
    scaledATokenBalance: BigNumber;
    usageAsCollateralEnabledOnUser: boolean;
    stableBorrowRate: BigNumber;
    scaledVariableDebt: BigNumber;
    principalStableDebt: BigNumber;
    stableBorrowLastUpdateTimestamp: BigNumber;
    aTokenincentivesUserIndex: BigNumber;
    vTokenincentivesUserIndex: BigNumber;
    sTokenincentivesUserIndex: BigNumber;
  };

  export type IncentivesControllerDataStruct = {
    userUnclaimedRewards: PromiseOrValue<BigNumberish>;
    emissionEndTimestamp: PromiseOrValue<BigNumberish>;
  };

  export type IncentivesControllerDataStructOutput = [BigNumber, BigNumber] & {
    userUnclaimedRewards: BigNumber;
    emissionEndTimestamp: BigNumber;
  };
}

export interface IUiPoolDataProviderInterface extends utils.Interface {
  functions: {
    "getReservesData(address,address)": FunctionFragment;
    "getReservesList(address)": FunctionFragment;
    "getSimpleReservesData(address)": FunctionFragment;
    "getUserReservesData(address,address)": FunctionFragment;
    "incentivesController()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "getReservesData"
      | "getReservesList"
      | "getSimpleReservesData"
      | "getUserReservesData"
      | "incentivesController"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "getReservesData",
    values: [PromiseOrValue<string>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "getReservesList",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "getSimpleReservesData",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserReservesData",
    values: [PromiseOrValue<string>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "incentivesController",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "getReservesData",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getReservesList",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSimpleReservesData",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserReservesData",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "incentivesController",
    data: BytesLike
  ): Result;

  events: {};
}

export interface IUiPoolDataProvider extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IUiPoolDataProviderInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    getReservesData(
      provider: PromiseOrValue<string>,
      user: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<
      [
        IUiPoolDataProvider.AggregatedReserveDataStructOutput[],
        IUiPoolDataProvider.UserReserveDataStructOutput[],
        BigNumber,
        IUiPoolDataProvider.IncentivesControllerDataStructOutput
      ]
    >;

    getReservesList(
      provider: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[string[]]>;

    getSimpleReservesData(
      provider: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<
      [
        IUiPoolDataProvider.AggregatedReserveDataStructOutput[],
        BigNumber,
        BigNumber
      ]
    >;

    getUserReservesData(
      provider: PromiseOrValue<string>,
      user: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[IUiPoolDataProvider.UserReserveDataStructOutput[], BigNumber]>;

    incentivesController(overrides?: CallOverrides): Promise<[string]>;
  };

  getReservesData(
    provider: PromiseOrValue<string>,
    user: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<
    [
      IUiPoolDataProvider.AggregatedReserveDataStructOutput[],
      IUiPoolDataProvider.UserReserveDataStructOutput[],
      BigNumber,
      IUiPoolDataProvider.IncentivesControllerDataStructOutput
    ]
  >;

  getReservesList(
    provider: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<string[]>;

  getSimpleReservesData(
    provider: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<
    [
      IUiPoolDataProvider.AggregatedReserveDataStructOutput[],
      BigNumber,
      BigNumber
    ]
  >;

  getUserReservesData(
    provider: PromiseOrValue<string>,
    user: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<[IUiPoolDataProvider.UserReserveDataStructOutput[], BigNumber]>;

  incentivesController(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    getReservesData(
      provider: PromiseOrValue<string>,
      user: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<
      [
        IUiPoolDataProvider.AggregatedReserveDataStructOutput[],
        IUiPoolDataProvider.UserReserveDataStructOutput[],
        BigNumber,
        IUiPoolDataProvider.IncentivesControllerDataStructOutput
      ]
    >;

    getReservesList(
      provider: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<string[]>;

    getSimpleReservesData(
      provider: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<
      [
        IUiPoolDataProvider.AggregatedReserveDataStructOutput[],
        BigNumber,
        BigNumber
      ]
    >;

    getUserReservesData(
      provider: PromiseOrValue<string>,
      user: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[IUiPoolDataProvider.UserReserveDataStructOutput[], BigNumber]>;

    incentivesController(overrides?: CallOverrides): Promise<string>;
  };

  filters: {};

  estimateGas: {
    getReservesData(
      provider: PromiseOrValue<string>,
      user: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getReservesList(
      provider: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getSimpleReservesData(
      provider: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getUserReservesData(
      provider: PromiseOrValue<string>,
      user: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    incentivesController(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    getReservesData(
      provider: PromiseOrValue<string>,
      user: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getReservesList(
      provider: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getSimpleReservesData(
      provider: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getUserReservesData(
      provider: PromiseOrValue<string>,
      user: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    incentivesController(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
