/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as sefldestructTransferSol from "./SefldestructTransfer.sol";
export type { sefldestructTransferSol };
