/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import type { Provider, TransactionRequest } from "@ethersproject/providers";
import type { PromiseOrValue } from "../../../../common";
import type {
  MockParaSwapAugustusRegistry,
  MockParaSwapAugustusRegistryInterface,
} from "../../../../contracts/mocks/swap/MockParaSwapAugustusRegistry";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "augustus",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "augustus",
        type: "address",
      },
    ],
    name: "isValidAugustus",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

const _bytecode =
  "0x60a060405234801561001057600080fd5b5060405161017b38038061017b83398101604081905261002f91610044565b60601b6001600160601b031916608052610072565b600060208284031215610055578081fd5b81516001600160a01b038116811461006b578182fd5b9392505050565b60805160601c60ef61008c600039806052525060ef6000f3fe6080604052348015600f57600080fd5b506004361060285760003560e01c8063fb04e17b14602d575b600080fd5b603c60383660046082565b6050565b6040516047919060ae565b60405180910390f35b7f00000000000000000000000000000000000000000000000000000000000000006001600160a01b0390811691161490565b6000602082840312156092578081fd5b81356001600160a01b038116811460a7578182fd5b9392505050565b90151581526020019056fea26469706673582212209509d8d4ea36f44f91a84c075ef68dc7a3bc2ad0c9ed5eda99de58c6bee6d2e264736f6c634300060c0033";

type MockParaSwapAugustusRegistryConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: MockParaSwapAugustusRegistryConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class MockParaSwapAugustusRegistry__factory extends ContractFactory {
  constructor(...args: MockParaSwapAugustusRegistryConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override deploy(
    augustus: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<MockParaSwapAugustusRegistry> {
    return super.deploy(
      augustus,
      overrides || {}
    ) as Promise<MockParaSwapAugustusRegistry>;
  }
  override getDeployTransaction(
    augustus: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(augustus, overrides || {});
  }
  override attach(address: string): MockParaSwapAugustusRegistry {
    return super.attach(address) as MockParaSwapAugustusRegistry;
  }
  override connect(signer: Signer): MockParaSwapAugustusRegistry__factory {
    return super.connect(signer) as MockParaSwapAugustusRegistry__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): MockParaSwapAugustusRegistryInterface {
    return new utils.Interface(_abi) as MockParaSwapAugustusRegistryInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): MockParaSwapAugustusRegistry {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as MockParaSwapAugustusRegistry;
  }
}
