/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ERC20__factory } from "./ERC20__factory";
export { IERC20__factory } from "./IERC20__factory";
export { IERC20Detailed__factory } from "./IERC20Detailed__factory";
export { Ownable__factory } from "./Ownable__factory";
