/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { MockAToken } from "./MockAToken";
export type { MockStableDebtToken } from "./MockStableDebtToken";
export type { MockVariableDebtToken } from "./MockVariableDebtToken";
