/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as base from "./base";
export type { base };
export type { AToken } from "./AToken";
export type { DelegationAwareAToken } from "./DelegationAwareAToken";
export type { IncentivizedERC20 } from "./IncentivizedERC20";
export type { StableDebtToken } from "./StableDebtToken";
export type { VariableDebtToken } from "./VariableDebtToken";
