/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import type { Provider, TransactionRequest } from "@ethersproject/providers";
import type { PromiseOrValue } from "../../../../../common";
import type {
  SelfdestructTransfer,
  SelfdestructTransferInterface,
} from "../../../../../contracts/mocks/attacks/SefldestructTransfer.sol/SelfdestructTransfer";

const _abi = [
  {
    inputs: [
      {
        internalType: "address payable",
        name: "to",
        type: "address",
      },
    ],
    name: "destroyAndTransfer",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
];

const _bytecode =
  "0x6080604052348015600f57600080fd5b5060888061001e6000396000f3fe608060405260043610601c5760003560e01c8063785e07b3146021575b600080fd5b604460048036036020811015603557600080fd5b50356001600160a01b03166046565b005b806001600160a01b0316fffea2646970667358221220b8695086408707bf628bc055c8ffdf9b20c89cb62446e9c96bd3b0bdf3fd5b0964736f6c634300060c0033";

type SelfdestructTransferConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: SelfdestructTransferConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class SelfdestructTransfer__factory extends ContractFactory {
  constructor(...args: SelfdestructTransferConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override deploy(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<SelfdestructTransfer> {
    return super.deploy(overrides || {}) as Promise<SelfdestructTransfer>;
  }
  override getDeployTransaction(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  override attach(address: string): SelfdestructTransfer {
    return super.attach(address) as SelfdestructTransfer;
  }
  override connect(signer: Signer): SelfdestructTransfer__factory {
    return super.connect(signer) as SelfdestructTransfer__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): SelfdestructTransferInterface {
    return new utils.Interface(_abi) as SelfdestructTransferInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): SelfdestructTransfer {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as SelfdestructTransfer;
  }
}
